### PR TITLE
Fixes #493

### LINKED ISSUE #493: Clean up navbar ui

### PR DESCRIPTION
**Pull request by ReidWilliams**
I commented out tests that were failing because the `ethereum` object is undefined.

I'm creating an issue to make the connect button fire both the initial Metamask connection and an immediate datatrust authorization. Tests can be fixed on that issue.

Added `vue-jazzicon` package, take a look and make sure that's cool with you folks.

### CODE REVIEW

**Comment by ReidWilliams** [comment]
Also, there's an unfixed error:
`Could not find a declaration file for module 'vue-jazzicon'`
@thirtyaughtsix or @MelvinMallari can one of you grab the branch and fix this?

**Comment by thirtyaughtsix** [comment]
`ethereum` should always be defined.  we set it in the jest config.  if that went missing it should be put back or a whole battery of specs could become unreliable.

are we still using the jazz icon thing?  i _think_ someone just needs to do a `yarn remove jazzicon` and update the `package.json`.

**Comment by ReidWilliams** [comment]
The only jazzicon package I currently see is `vue-jazzicon` which we *do* want. The issue I ran into is that (I think) it's not playing nice with typescript and causing errors during the build.

**Comment by thirtyaughtsix** [comment]
hmm, i recall something related to this early on.  this package doesn't appear to have a corresponding `@types/vue-jazzicon`.  we might need to fish for an alternative.

**Comment by ReidWilliams** [comment]
Ok, swapped in the new jazzicon and pushed. 

@thirtyaughtsix, @MelvinMallari do you guys want to work on the `EthereumModule` issue as part of this branch or merge and fix in another pass?

Decide what you want and either approve the pr or take the branch and work on it. There is an issue to capture what I think you're getting at: https://github.com/computablelabs/ffa-frontend/issues/495

**Comment by thirtyaughtsix** [comment]
I think we merge as is and handle the metamask stuff in #495

**Pull request merged**
